const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const LS={get:(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch(e){return d}},set:(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}};
const inr=n=>"₹"+n.toLocaleString("en-IN"),qs=new URLSearchParams(location.search),page=document.body.dataset.page;
const byId=id=>PRODUCTS.find(p=>p.id==id);
const PH="+91 90000 12345",EM="hello@newfashioncafe.example"; // DUMMY demo contact details
/* ---------- garment SVG visuals ---------- */
const SH={tee:"M62 50L88 38Q100 52 112 38L138 50L170 88L148 104L140 94V198H60V94L52 104L30 88Z",
polo:"M62 50L88 38L100 60L112 38L138 50L170 88L148 104L140 94V198H60V94L52 104L30 88Z",
shirt:"M62 48L88 36L100 56L112 36L138 48L172 120L150 128L140 100V204H60V100L50 128L28 120Z",
hoodie:"M60 58Q100 18 140 58L176 150L154 160L140 120V200H60V120L46 160L24 150Z",
jacket:"M60 46L88 34L100 50L112 34L140 46L174 150L152 158L140 110V204H60V110L48 158L26 150Z",
jeans:"M62 28H138L152 208H108L100 96L92 208H48Z",
dress:"M80 28H120L128 84L162 208H38L72 84Z",kurti:"M64 34H136L152 72L142 92V216H58V92L48 72Z",
set:"M62 40L88 30Q100 44 112 30L138 40L160 72L142 84V120H58V84L40 72Z M62 128H138L146 200H108L100 150L92 200H54Z"};
function shade(h,a){const n=parseInt(h.slice(1),16);let r=n>>16,g=n>>8&255,b=n&255;const f=c=>Math.max(0,Math.min(255,c+a));return`rgb(${f(r)},${f(g)},${f(b)})`}
function art(p,v=0){const c=v?shade(p.color,v*18):p.color,dk=shade(p.color,-45),bg=document.documentElement.dataset.theme==="dark"?"#26231f":"#efe9df";
let x=`<path d="${SH[p.type]}" fill="${c}" stroke="${dk}" stroke-width="1.5" stroke-linejoin="round"/>`;
if(p.type==="hoodie")x+=`<path d="M82 62Q100 84 118 62M100 84V110M76 160H124V184H76Z" fill="none" stroke="${dk}" stroke-width="1.5"/>`;
if(p.type==="shirt"||p.type==="polo"||p.type==="jacket")x+=`<path d="M100 56V204" stroke="${dk}" stroke-width="1.5"/>`+(p.type==="jeans"?"":`<circle cx="100" cy="90" r="2" fill="${dk}"/><circle cx="100" cy="120" r="2" fill="${dk}"/>`);
if(p.type==="jeans")x+=`<path d="M62 44H138" stroke="${dk}" stroke-width="1.5"/>`;
if(p.type==="tee"&&p.category==="T-Shirts"&&v===1)x+=`<text x="100" y="130" text-anchor="middle" font-family="Georgia" font-size="16" fill="${dk}" opacity=".6">NFC</text>`;
return`<svg viewBox="0 0 200 240" role="img" aria-label="${p.name} product image" xmlns="http://www.w3.org/2000/svg"><rect width="200" height="240" fill="${bg}"/><ellipse cx="100" cy="224" rx="60" ry="6" fill="#0002"/>${x}</svg>`}
const logo=`<a class="logo" href="index.html" aria-label="New Fashion Cafe home"><svg class="full" width="210" height="44" viewBox="0 0 210 44"><rect width="44" height="44" rx="10" fill="currentColor"/><path d="M22 10a3.5 3.5 0 1 1 3.5 3.5c-2 .6-3.5 2-3.5 4v1.5L9 29h26L22 19" fill="none" stroke="var(--bg)" stroke-width="2" stroke-linejoin="round"/><text x="22" y="40" font-size="7" fill="var(--bg)" text-anchor="middle" font-family="Georgia" font-weight="700">NFC</text><text x="54" y="20" font-size="16" font-family="Georgia" font-weight="700" letter-spacing="2" fill="currentColor">NEW FASHION</text><text x="54" y="37" font-size="12" font-family="Georgia" letter-spacing="9" fill="var(--ac)">CAFE</text></svg><svg class="cmp" width="40" height="40" viewBox="0 0 44 44"><rect width="44" height="44" rx="10" fill="currentColor"/><path d="M22 10a3.5 3.5 0 1 1 3.5 3.5c-2 .6-3.5 2-3.5 4v1.5L9 29h26L22 19" fill="none" stroke="var(--bg)" stroke-width="2"/><text x="22" y="40" font-size="7" fill="var(--bg)" text-anchor="middle" font-family="Georgia" font-weight="700">NFC</text></svg></a>`;
/* ---------- state ---------- */
const cart=()=>LS.get("nfc_cart",[]),wish=()=>LS.get("nfc_wish",[]);
function toast(m){let t=$("#toast");const d=document.createElement("div");d.textContent="✓ "+m;t.append(d);setTimeout(()=>d.remove(),2400)}
function counts(){$("#cc").textContent=cart().reduce((a,i)=>a+i.qty,0);$("#wc").textContent=wish().length}
function addCart(id,size,qty=1){const p=byId(id);if(!p.stock)return toast("Out of stock");size=size||p.sizes[1]||p.sizes[0];const c=cart(),f=c.find(i=>i.id==id&&i.size==size);f?f.qty+=qty:c.push({id:+id,size,qty});LS.set("nfc_cart",c);counts();toast("Added to cart")}
function toggleWish(id){let w=wish();if(w.includes(+id)){w=w.filter(x=>x!=id);toast("Removed from wishlist")}else{w.push(+id);toast("Added to wishlist")}LS.set("nfc_wish",w);counts();$$(`.wl[data-id="${id}"]`).forEach(b=>b.textContent=w.includes(+id)?"♥":"♡");if(page==="wishlist")wishlistPage()}
function card(p){const w=wish().includes(p.id);return`<article class="card"><button class="wl" data-id="${p.id}" aria-label="Toggle wishlist for ${p.name}">${w?"♥":"♡"}</button><a class="im" href="product.html?id=${p.id}">${art(p)}</a><div class="bd"><small>${p.category} · ${p.gender}</small><h3 style="font-size:1rem;margin:2px 0"><a href="product.html?id=${p.id}">${p.name}</a></h3><div>★ ${p.rating}</div><div class="pr">${inr(p.price)}<s>${inr(p.oldPrice)}</s><em>${p.discount}% off</em></div><div class="row"><button class="btn sm" data-cart="${p.id}"${p.stock?"":" disabled"}>${p.stock?"Add to Cart":"Sold out"}</button><button class="btn sm o" data-qv="${p.id}">Quick View</button></div></div></article>`}
/* ---------- layout ---------- */
const NAV=[["index","Home"],["shop","Shop"],["categories","Categories"],["shop?new=1","New Arrivals"],["shop?sale=1","Offers"],["lookbook","Lookbook"],["about","About"],["contact","Contact"]];
function layout(){const th=LS.get("nfc_theme","light");document.documentElement.dataset.theme=th;
$("#app-header").innerHTML=`<header><div class="wrap nav">${logo}<nav id="nav" aria-label="Main">${NAV.map(n=>`<a href="${n[0].replace(/^(\w[\w-]*)(\?.*)?$/,"$1.html$2")}" class="${n[0]===page?"on":""}">${n[1]}</a>`).join("")}</nav><div class="ic"><button id="sb" aria-label="Search">⌕</button><button onclick="location='wishlist.html'" aria-label="Wishlist">♡<b id="wc">0</b></button><button onclick="location='cart.html'" aria-label="Cart">🛍<b id="cc">0</b></button><button id="dm" aria-label="Toggle dark mode">◐</button><button id="burger" aria-label="Menu">☰</button></div></div></header>`;
$("#app-footer").innerHTML=`<footer><div class="wrap"><div class="fg"><div>${logo}<p class="mu" style="margin-top:10px">A modern local fashion store in Hubli, Karnataka, owned by Gopal.</p></div><div><h3>Links</h3><a href="shop.html">Shop</a><a href="lookbook.html">Lookbook</a><a href="style-guide.html">Style Guide</a><a href="size-guide.html">Size Guide</a><a href="order-tracking.html">Track Order</a></div><div><h3>Categories</h3><a href="shop.html?g=Men">Men</a><a href="shop.html?g=Women">Women</a><a href="shop.html?g=Kids">Kids</a></div><div><h3>Contact (demo)</h3><p class="mu">Hubli, Karnataka, India<br>${PH}<br>${EM}</p><form id="nl" style="display:flex;gap:6px;margin-top:10px"><input type="email" required aria-label="Newsletter email" placeholder="Email"><button class="btn sm">Join</button></form></div></div><p class="mu" style="text-align:center;margin-top:28px">© 2026 New Fashion Cafe. All Rights Reserved. Demo store — no real orders or payments.</p></div></footer><div id="toast" aria-live="polite"></div><a class="wa" href="https://wa.me/919000012345?text=${encodeURIComponent("Hello New Fashion Cafe, I would like to know more about your clothing collection.")}" target="_blank" rel="noopener" aria-label="WhatsApp (demo number)">WA</a><div class="modal" id="md"><div><button class="x" aria-label="Close">×</button><div id="mb"></div></div></div><div class="modal" id="sm"><div><button class="x" aria-label="Close">×</button><input id="si" placeholder="Search products…" aria-label="Search products"><div id="sr" class="grid" style="margin-top:16px"></div></div></div>`;
counts();$("#burger").onclick=()=>$("#nav").classList.toggle("open");
$("#dm").onclick=()=>{const t=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=t;LS.set("nfc_theme",t)};
$("#sb").onclick=()=>{$("#sm").classList.add("show");$("#si").focus()};
$("#si").oninput=e=>{const q=e.target.value.toLowerCase().trim(),r=q?PRODUCTS.filter(p=>(p.name+p.category+p.gender+p.description).toLowerCase().includes(q)):[];$("#sr").innerHTML=q?(r.map(card).join("")||"<p>No products found. Try another search.</p>"):""};
$("#nl").onsubmit=e=>{e.preventDefault();toast("Subscribed (demo)");e.target.reset()};
$$(".x").forEach(b=>b.onclick=()=>b.closest(".modal").classList.remove("show"));$$(".modal").forEach(m=>m.onclick=e=>{if(e.target===m)m.classList.remove("show")});
document.addEventListener("keydown",e=>{if(e.key==="Escape")$$(".modal").forEach(m=>m.classList.remove("show"))});
document.addEventListener("click",e=>{const t=e.target;if(t.dataset.cart)addCart(t.dataset.cart);if(t.classList.contains("wl"))toggleWish(t.dataset.id);if(t.dataset.qv)quick(t.dataset.qv)});
const io=new IntersectionObserver(es=>es.forEach(x=>x.isIntersecting&&x.target.classList.add("in")));window.reveal=()=>$$(".rv:not(.in)").forEach(el=>io.observe(el))}
function quick(id){const p=byId(id);$("#mb").innerHTML=`<div class="pd"><div class="big">${art(p)}</div><div><h2>${p.name}</h2><p>★ ${p.rating} · ${p.category}</p><p class="pr" style="font-size:1.3rem">${inr(p.price)}<s>${inr(p.oldPrice)}</s><em>${p.discount}% off</em></p><p class="mu">${p.description}</p><p><a class="btn sm" href="product.html?id=${p.id}">Full details</a></p></div></div>`;$("#md").classList.add("show")}
/* ---------- pages ---------- */
const M=h=>$("#main").innerHTML=h;
const head=(t,s)=>`<div class="banner"><div class="wrap"><span class="tag">New Fashion Cafe</span><h1 style="font-size:clamp(2rem,5vw,3rem)">${t}</h1>${s?`<p class="mu">${s}</p>`:""}</div></div>`;
const R={
index(){const cats=[["Men","g=Men"],["Women","g=Women"],["Kids","g=Kids"],["T-Shirts","c=T-Shirts"],["Shirts","c=Shirts"],["Jeans","c=Jeans"],["Hoodies","c=Hoodies"],["New Arrivals","new=1"]];
M(`<div class="wrap hero"><div><span class="tag">Hubli · Karnataka</span><h1>STYLE THAT SPEAKS FOR YOU</h1><p>Discover everyday fashion, modern essentials and statement pieces at New Fashion Cafe.</p><a class="btn" href="shop.html">Shop Now</a> <a class="btn o" href="shop.html?new=1">Explore Collection</a></div><div class="art">${art(byId(1),1)}</div></div>
<section class="wrap rv"><h2>Featured Categories</h2><div class="cats">${cats.map(c=>`<a class="cat" href="shop.html?${c[1]}">${c[0]}</a>`).join("")}</div></section>
<section class="wrap rv"><h2>New Arrivals</h2><div class="grid">${PRODUCTS.filter(p=>p.isNew).slice(0,8).map(card).join("")}</div></section>
<section class="wrap rv"><div class="box" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:24px;align-items:center"><div><span class="tag">Trending Collection</span><h2>Oversized, Denim & Everyday Layers</h2><p class="mu" style="margin-bottom:18px">Our most-loved pieces this season, picked for comfort and easy styling.</p><a class="btn" href="shop.html?f=1">Explore Collection</a></div><div class="art" style="display:flex">${art(byId(26),0)}${art(byId(28),0)}</div></div></section>
<section class="offer"><span class="tag">Special Offer</span><h1>UP TO 40% OFF</h1><p>ON SELECTED STYLES</p><div class="cd" id="cd"></div><a class="btn" href="shop.html?sale=1">Shop Offers</a></section>
<section class="wrap rv"><h2>Why Choose Us</h2><div class="feat">${[["Quality First","Comfortable and carefully selected clothing."],["Trendy Styles","Modern styles for everyday fashion."],["Affordable Prices","Fashion at reasonable prices."],["Local Store","Serving customers in Hubli."]].map(f=>`<div><h3>${f[0]}</h3><p class="mu">${f[1]}</p></div>`).join("")}</div></section>
<section class="wrap rv"><h2>Customer Reviews <small class="mu" style="font-size:.9rem">(sample/demo reviews)</small></h2><div class="feat">${[["Rahul","Great fit and the fabric feels soft."],["Ananya","Loved the kurti, easy to style."],["Sneha","Good prices and nice collection."],["Arjun","Hoodie quality is excellent."]].map(r=>`<div><div style="display:flex;gap:10px;align-items:center"><span class="chip on" style="border-radius:50%;padding:8px 14px">${r[0][0]}</span><b>${r[0]}</b></div><p>★★★★★</p><p class="mu">${r[1]}</p></div>`).join("")}</div></section>
<section class="wrap rv"><div class="box"><h2>Visit Us</h2><p><b>New Fashion Cafe</b> · Owner: Gopal<br>Hubli, Karnataka, India<br>Mon–Sun, 10:00 AM – 9:00 PM · ${PH} · ${EM}<br><span class="mu">(demo contact details)</span></p><p style="margin-top:12px"><a class="btn sm" target="_blank" rel="noopener" href="https://www.google.com/maps/search/Hubli+Karnataka">Location</a> <a class="btn sm o" target="_blank" rel="noopener" href="https://wa.me/919000012345">WhatsApp</a></p></div></section>`);
const end=Date.now()+(LS.get("nfc_end",0)>Date.now()?LS.get("nfc_end",0)-Date.now():0)||0;let E=LS.get("nfc_end",0);if(E<Date.now()){E=Date.now()+3*864e5;LS.set("nfc_end",E)}
const tick=()=>{let s=Math.max(0,E-Date.now())/1e3|0;$("#cd").innerHTML=[["Days",86400],["Hrs",3600],["Min",60],["Sec",1]].map(u=>{const v=s/u[1]|0;s-=v*u[1];return`<div><b>${String(v).padStart(2,"0")}</b>${u[0]}</div>`}).join("")};tick();setInterval(tick,1000)},
shop(){const g=qs.get("g")||"",c=qs.get("c")||"";M(head("Shop","Browse the full collection.")+`<div class="wrap" style="padding-top:28px"><div class="shop"><aside><label for="q">Search</label><input id="q" value="${qs.get("q")||""}"><label>Gender</label><select id="g">${["","Men","Women","Kids"].map(x=>`<option ${x===g?"selected":""} value="${x}">${x||"All"}</option>`).join("")}</select><label>Category</label><select id="c">${["",...new Set(PRODUCTS.map(p=>p.category))].map(x=>`<option ${x===c?"selected":""} value="${x}">${x||"All"}</option>`).join("")}</select><label>Size</label><select id="s">${["","S","M","L","XL","XXL"].map(x=>`<option value="${x}">${x||"Any"}</option>`).join("")}</select><label>Max price: <span id="pv">3000</span></label><input id="p" type="range" min="300" max="3000" step="100" value="3000"><label>Min rating</label><select id="r"><option value="0">Any</option><option>4</option><option>4.5</option></select><label><input type="checkbox" id="a" style="width:auto"> In stock only</label><label>Sort</label><select id="o"><option value="f">Featured</option><option value="pl">Price: Low to High</option><option value="ph">Price: High to Low</option><option value="n">Newest</option><option value="r">Best Rated</option><option value="d">Discount</option></select></aside><div><p class="mu" id="n"></p><div class="grid" id="gr"></div></div></div></div>`);
const up=()=>{const q=$("#q").value.toLowerCase(),f=PRODUCTS.filter(p=>(p.name+p.category+p.description).toLowerCase().includes(q)&&(!$("#g").value||p.gender===$("#g").value)&&(!$("#c").value||p.category===$("#c").value)&&(!$("#s").value||p.sizes.includes($("#s").value))&&p.price<=+$("#p").value&&p.rating>=+$("#r").value&&(!$("#a").checked||p.stock)&&(!qs.get("new")||p.isNew)&&(!qs.get("sale")||p.discount>=30)&&(!qs.get("f")||p.featured));
const o=$("#o").value;f.sort((a,b)=>o==="pl"?a.price-b.price:o==="ph"?b.price-a.price:o==="n"?b.id-a.id:o==="r"?b.rating-a.rating:o==="d"?b.discount-a.discount:b.featured-a.featured);$("#pv").textContent=$("#p").value;$("#n").textContent=f.length+" products";$("#gr").innerHTML=f.map(card).join("")||"<p>No products found. Try another search.</p>"};
$$("aside input,aside select").forEach(e=>e.oninput=up);up()},
product(){const p=byId(qs.get("id"))||PRODUCTS[0];let sz=p.sizes[1]||p.sizes[0],q=1;document.title=p.name+" | New Fashion Cafe";
M(`<div class="wrap" style="padding-top:36px"><div class="pd"><div><div class="big" id="bg">${art(p,1)}</div><div class="th">${[0,1,2].map(v=>`<span data-v="${v}">${art(p,v)}</span>`).join("")}</div></div><div><span class="tag">${p.gender} · ${p.category}</span><h1 style="font-size:2.2rem">${p.name}</h1><p>★ ${p.rating} (demo reviews)</p><p class="pr" style="font-size:1.5rem">${inr(p.price)}<s>${inr(p.oldPrice)}</s><em>${p.discount}% off</em></p><p class="mu">${p.description}</p><label>Size <a href="#" id="sg" style="text-decoration:underline">Size guide</a></label><div class="chips" id="sz">${p.sizes.map(s=>`<button class="chip ${s===sz?"on":""}">${s}</button>`).join("")}</div><label>Quantity</label><div class="chips"><button class="chip" id="mi">−</button><span class="chip" id="qv">1</span><button class="chip" id="pl">+</button></div><p style="margin:16px 0"><button class="btn" id="ac"${p.stock?"":" disabled"}>Add to Cart</button> <button class="btn o" id="bn"${p.stock?"":" disabled"}>Buy Now</button> <button class="btn o wlb" data-id="${p.id}" onclick="toggleWish(${p.id})">Wishlist</button></p><table>${[["Material","100% Cotton blend"],["Fit",p.id%2?"Regular":"Relaxed"],["Wash care","Machine wash cold"],["Pattern","Solid"],["Sleeve",p.type==="jeans"?"—":"As per style"],["Origin","India"]].map(r=>`<tr><th>${r[0]}</th><td>${r[1]}</td></tr>`).join("")}</table></div></div><section><h2>Related Products</h2><div class="grid">${PRODUCTS.filter(x=>x.category===p.category&&x.id!==p.id||x.gender===p.gender&&x.type===p.type&&x.id!==p.id).slice(0,4).map(card).join("")}</div></section></div>`);
$$(".th span").forEach(s=>s.onclick=()=>$("#bg").innerHTML=art(p,+s.dataset.v));$$("#sz .chip").forEach(b=>b.onclick=()=>{sz=b.textContent;$$("#sz .chip").forEach(x=>x.classList.toggle("on",x===b))});
$("#mi").onclick=()=>$("#qv").textContent=q=Math.max(1,q-1);$("#pl").onclick=()=>$("#qv").textContent=++q;$("#ac").onclick=()=>addCart(p.id,sz,q);$("#bn").onclick=()=>{addCart(p.id,sz,q);location="checkout.html"};
$("#sg").onclick=e=>{e.preventDefault();$("#mb").innerHTML=sizeTables();$("#md").classList.add("show")}},
categories(){const T={Men:["T-Shirts","Shirts","Jeans","Hoodies","Jackets","Trousers"],Women:["Tops","Dresses","Kurtis","Jeans","Jackets","Casual Wear"],Kids:["T-Shirts","Sets","Jeans","Hoodies"]};
M(head("Categories","Shop by collection.")+`<div class="wrap">${Object.entries(T).map(([g,l])=>`<section><h2>${g}</h2><div class="cats">${l.map(c=>`<a class="cat" href="shop.html?g=${g}&c=${c}">${c}</a>`).join("")}</div></section>`).join("")}</div>`)},
wishlist(){wishlistPage()},cart(){cartPage()},
checkout(){const c=cart();if(!c.length)return M(head("Checkout")+`<div class="empty"><h2>Your cart is empty</h2><a class="btn" href="shop.html">Shop Now</a></div>`);const t=totals(c);
const F=(id,l,v="",t="text")=>`<div><label for="${id}">${l}</label><input id="${id}" type="${t}" value="${v}"><span class="err" id="e-${id}"></span></div>`;
M(head("Checkout","Demo checkout — no real payment is taken.")+`<div class="wrap" style="padding-top:28px"><div class="two"><form id="cf" novalidate class="box"><h3>Customer</h3><div class="form2">${F("fn","Full name")}${F("ph","Phone")}${F("em","Email","","email")}</div><h3 style="margin-top:20px">Delivery address</h3><div class="form2">${F("h1","House/Building")}${F("st","Street")}${F("ar","Area")}${F("ct","City","Hubli")}${F("sa","State","Karnataka")}${F("pn","PIN code")}</div><h3 style="margin-top:20px">Payment (simulation)</h3><div class="chips">${["Cash on Delivery","UPI","Card"].map((x,i)=>`<label style="margin:0"><input type="radio" name="pm" value="${x}" ${i?"":"checked"} style="width:auto"> ${x}</label>`).join(" &nbsp; ")}</div><p style="margin-top:16px"><button class="btn">Place Order</button></p></form><div class="box sum"><h3>Summary</h3>${sumHtml(t)}</div></div></div>`);
$("#cf").onsubmit=e=>{e.preventDefault();let ok=true;const rule={fn:v=>v.trim().length>1,ph:v=>/^[6-9]\d{9}$/.test(v.replace(/\D/g,"").slice(-10)),em:v=>/^\S+@\S+\.\S+$/.test(v),h1:v=>v.trim(),st:v=>v.trim(),ar:v=>v.trim(),ct:v=>v.trim(),sa:v=>v.trim(),pn:v=>/^\d{6}$/.test(v)};
for(const k in rule){const el=$("#"+k),g=!!rule[k](el.value);el.classList.toggle("bad",!g);$("#e-"+k).textContent=g?"":"Please check this field";if(!g)ok=false}if(!ok)return;
const n=LS.get("nfc_ocount",0)+1;LS.set("nfc_ocount",n);const d=new Date(),id="NFC"+d.getFullYear()+String(d.getMonth()+1).padStart(2,"0")+String(d.getDate()).padStart(2,"0")+String(n).padStart(3,"0");
const o={id,name:$("#fn").value,items:c,total:t.total,pay:document.querySelector("[name=pm]:checked").value,addr:["h1","st","ar","ct","sa","pn"].map(k=>$("#"+k).value).join(", "),placed:Date.now(),eta:Date.now()+4*864e5};
LS.set("nfc_orders",[o,...LS.get("nfc_orders",[])]);LS.set("nfc_last",id);LS.set("nfc_cart",[]);location="order-confirmation.html"}},
"order-confirmation"(){const o=LS.get("nfc_orders",[]).find(x=>x.id===LS.get("nfc_last"));if(!o)return M(head("No recent order")+`<div class="empty"><a class="btn" href="shop.html">Shop Now</a></div>`);
M(head("ORDER PLACED SUCCESSFULLY","Demo order — stored only in your browser.")+`<div class="wrap" style="padding-top:28px"><div class="box"><p><b>Order ID:</b> ${o.id}<br><b>Name:</b> ${o.name}<br><b>Payment:</b> ${o.pay}<br><b>Delivery:</b> ${o.addr}<br><b>Estimated delivery:</b> ${new Date(o.eta).toDateString()}<br><b>Total:</b> ${inr(o.total)}</p>${o.items.map(i=>`<p class="mu">${byId(i.id).name} · ${i.size} × ${i.qty}</p>`).join("")}<p style="margin-top:14px"><a class="btn" href="order-tracking.html?id=${o.id}">Track Order</a></p></div></div>`);toast("Order placed successfully")},
"order-tracking"(){const os=LS.get("nfc_orders",[]);M(head("Track Order","Simulated progress — no delivery API.")+`<div class="wrap" style="padding-top:28px"><label for="oi">Order ID</label><div style="display:flex;gap:8px;max-width:420px"><input id="oi" value="${qs.get("id")||LS.get("nfc_last","")||""}"><button class="btn" id="tb">Track</button></div><div id="tr"></div></div>`);
const S=["Order Confirmed","Preparing","Packed","Out for Delivery","Delivered"],show=()=>{const o=os.find(x=>x.id===$("#oi").value.trim());if(!o)return $("#tr").innerHTML="<p class='err'>Order not found on this device.</p>";const s=Math.min(4,(Date.now()-o.placed)/15e3|0);$("#tr").innerHTML=`<div class="steps">${S.map((x,i)=>`<div class="${i<=s?"d":""}"><i>${i<=s?"✓":i+1}</i>${x}</div>`).join("")}</div><p class="mu">Progress advances automatically every ~15 seconds (demo).</p>`};$("#tb").onclick=show;show();setInterval(()=>$("#oi").value&&show(),5000)},
lookbook(){const L=[["Casual Edit","Everyday clothing.",[1,9,14]],["Street Style","Modern oversized and streetwear looks.",[4,26,11]],["Weekend Looks","Relaxed fashion.",[7,27,15]],["Festive Collection","Traditional and modern combinations.",[18,17,19]]];
M(head("Lookbook","A magazine-style edit.")+`<div class="wrap">${L.map((l,i)=>`<section class="rv"><span class="tag">0${i+1}</span><h2>${l[0].toUpperCase()}</h2><p class="mu">${l[1]}</p><div class="grid" style="margin:16px 0">${l[2].map(id=>`<div class="art" style="background:var(--card)">${art(byId(id),1)}</div>`).join("")}</div><a class="btn" href="shop.html?q=${encodeURIComponent(byId(l[2][0]).category)}">Shop this look</a></section>`).join("")}</div>`);reveal()},
"style-guide"(){const G=[["How to Style Oversized T-Shirts","Pair with straight jeans or joggers and clean sneakers; keep the bottom slim to balance the volume."],["How to Match Jeans","Dark denim suits shirts and polos; light denim pairs well with white or black tees."],["Casual Outfit Ideas","Plain tee + blue jeans + overshirt for an easy everyday look."],["College Outfit Ideas","Graphic tee, cargo pants and a light jacket; comfortable all day."],["Weekend Outfit Ideas","Hoodie with joggers, or a relaxed shirt with chinos."],["Color Combination Guide","Neutrals (black, white, beige) go with everything; add one muted accent such as olive or navy."]];
M(head("Style Guide","Simple outfit ideas.")+`<div class="wrap"><div class="feat" style="padding:40px 0">${G.map((g,i)=>`<div><div style="aspect-ratio:5/4;overflow:hidden">${art(byId([1,9,6,12,25,4][i]),1)}</div><h3 style="margin-top:12px">${g[0]}</h3><p class="mu">${g[1]}</p></div>`).join("")}</div></div>`)},
"size-guide"(){M(head("Size Guide","Measurements in inches.")+`<div class="wrap" style="padding:30px 20px">${sizeTables()}<div class="box" style="margin-top:30px"><h2>Find My Size</h2><div class="form2"><div><label for="fg">Gender</label><select id="fg"><option>Men</option><option>Women</option></select></div><div><label for="fh">Height (cm)</label><input id="fh" type="number" value="170"></div><div><label for="fw">Weight (kg)</label><input id="fw" type="number" value="65"></div><div><label for="fc">Chest (in)</label><input id="fc" type="number" value="38"></div><div><label for="ff">Fit</label><select id="ff"><option>Regular</option><option>Slim</option><option>Oversized</option></select></div></div><p><button class="btn" id="fb" style="margin-top:14px">Recommend</button></p><h3 id="fr" style="margin-top:14px"></h3><p class="mu">This is a general size recommendation and may vary by product.</p></div></div>`);
$("#fb").onclick=()=>{const c=+$("#fc").value,w=+$("#fw").value;let i=c<=36?0:c<=38?1:c<=40?2:c<=42?3:4;if(w>85)i=Math.max(i,3);i+={Slim:-1,Regular:0,Oversized:1}[$("#ff").value];i=Math.max(0,Math.min(4,i));$("#fr").textContent="Recommended Size: "+["S","M","L","XL","XXL"][i]}},
about(){M(head("ABOUT NEW FASHION CAFE")+`<div class="wrap" style="padding:40px 20px;max-width:800px"><p>New Fashion Cafe is a local fashion store based in Hubli, Karnataka, owned by Gopal. We focus on stylish and affordable clothing for men, women and kids, with everyday fashion that's easy to wear.</p><p style="margin-top:14px">Our aim is a customer-focused shopping experience: carefully selected pieces, honest prices and friendly service.</p></div>`)},
contact(){M(head("GET IN TOUCH","New Fashion Cafe · Owner: Gopal · Hubli, Karnataka, India")+`<div class="wrap" style="padding-top:28px"><div class="two"><form id="ctf" class="box" novalidate><div><label for="cn">Name</label><input id="cn"><span class="err"></span></div><div><label for="ce">Email</label><input id="ce" type="email"><span class="err"></span></div><div><label for="cp">Phone</label><input id="cp"><span class="err"></span></div><div><label for="cm">Message</label><textarea id="cm" rows="5"></textarea><span class="err"></span></div><p style="margin-top:14px"><button class="btn">Submit</button></p><p id="ok" style="margin-top:12px;font-weight:600"></p></form><div class="box"><p>Phone: ${PH}<br>Email: ${EM}<br><span class="mu">Dummy/demo contact details.</span></p></div></div></div>`);
$("#ctf").onsubmit=e=>{e.preventDefault();const r=[["cn",v=>v.trim().length>1],["ce",v=>/^\S+@\S+\.\S+$/.test(v)],["cp",v=>/^\d{10}$/.test(v.replace(/\D/g,"").slice(-10))],["cm",v=>v.trim().length>4]];let ok=true;r.forEach(([k,f])=>{const el=$("#"+k),g=f(el.value);el.classList.toggle("bad",!g);el.nextElementSibling.textContent=g?"":"Please check this field";if(!g)ok=false});if(ok){$("#ok").textContent="Thank you! Your message has been received.";toast("Message submitted");e.target.reset()}}}};
/* ---------- shared renderers ---------- */
function sizeTables(){const T=(t,h,r)=>`<h3 style="margin:18px 0 8px">${t}</h3><div style="overflow-x:auto"><table><tr>${h.map(x=>`<th>${x}</th>`).join("")}</tr>${r.map(x=>`<tr>${x.map(y=>`<td>${y}</td>`).join("")}</tr>`).join("")}</table></div>`;
return T("T-Shirts",["Size","Chest","Length"],[["S",'36"','26"'],["M",'38"','27"'],["L",'40"','28"'],["XL",'42"','29"'],["XXL",'44"','30"']])+T("Shirts",["Size","Chest","Length"],[["S",'38"','28"'],["M",'40"','29"'],["L",'42"','30"'],["XL",'44"','31"'],["XXL",'46"','32"']])+T("Bottoms",["Size","Waist","Length"],[["28",'28"','39"'],["30",'30"','40"'],["32",'32"','41"'],["34",'34"','41"'],["36",'36"','42"']])}
function totals(c){let sub=0,disc=0;c.forEach(i=>{const p=byId(i.id);sub+=p.oldPrice*i.qty;disc+=(p.oldPrice-p.price)*i.qty});const net=sub-disc,del=net>=1999||!net?0:99;return{sub,disc,del,total:net+del}}
const sumHtml=t=>`<div><span>Subtotal</span><span>${inr(t.sub)}</span></div><div><span>Discount</span><span>−${inr(t.disc)}</span></div><div><span>Delivery</span><span>${t.del?inr(t.del):"FREE"}</span></div><div class="mu"><span>Est. delivery</span><span>3–5 days</span></div><hr><div class="serif" style="font-size:1.2rem"><b>Total</b><b>${inr(t.total)}</b></div>`;
function cartPage(){const c=cart();if(!c.length)return M(head("Cart")+`<div class="empty"><h2>Your cart is empty</h2><p>Add something you love.</p><br><a class="btn" href="shop.html">Shop Now</a></div>`);
M(head("Shopping Cart")+`<div class="wrap" style="padding-top:20px"><div class="two"><div>${c.map((i,n)=>{const p=byId(i.id);return`<div class="line">${art(p)}<div><b>${p.name}</b><br><select data-sz="${n}" aria-label="Size" style="width:auto">${p.sizes.map(s=>`<option ${s===i.size?"selected":""}>${s}</option>`).join("")}</select><br>${inr(p.price)}</div><div><div class="chips"><button class="chip" data-q="${n}" data-d="-1">−</button><span class="chip">${i.qty}</span><button class="chip" data-q="${n}" data-d="1">+</button></div><button class="btn sm o" data-rm="${n}">Remove</button></div></div>`}).join("")}</div><div class="box sum"><h3>Order Summary</h3>${sumHtml(totals(c))}<a class="btn" style="width:100%;text-align:center;margin-top:12px" href="checkout.html">Checkout</a></div></div></div>`);
$$("[data-q]").forEach(b=>b.onclick=()=>{const c=cart();c[b.dataset.q].qty=Math.max(1,c[b.dataset.q].qty+ +b.dataset.d);LS.set("nfc_cart",c);counts();cartPage()});
$$("[data-rm]").forEach(b=>b.onclick=()=>{const c=cart();c.splice(b.dataset.rm,1);LS.set("nfc_cart",c);counts();toast("Product removed");cartPage()});
$$("[data-sz]").forEach(s=>s.onchange=()=>{const c=cart();c[s.dataset.sz].size=s.value;LS.set("nfc_cart",c)})}
function wishlistPage(){const w=wish().map(byId);M(head("Wishlist")+(w.length?`<div class="wrap" style="padding-top:28px"><div class="grid">${w.map(card).join("")}</div></div>`:`<div class="empty"><h2>Your wishlist is empty</h2><p>Tap the heart on any product to save it.</p><br><a class="btn" href="shop.html">Browse Shop</a></div>`))}
layout();R[page]();reveal();
